from PyQt5 import QtCore, QtGui, QtWidgets

class UI_MainWindow(object):
    def buildUiElements(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("images/icon.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("mainwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        with open('styles/widget.css', 'r') as f:
            style_widget = f.read()
        self.widget.setStyleSheet(style_widget)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.horizontalLayout_body = QtWidgets.QHBoxLayout()
        self.horizontalLayout_body.setContentsMargins(15, 10, 15, 10)
        self.horizontalLayout_body.setSpacing(15)
        self.horizontalLayout_body.setObjectName("horizontalLayout_body")
        self.verticalLayout_musiclist = QtWidgets.QVBoxLayout()
        self.verticalLayout_musiclist.setSpacing(4)
        self.verticalLayout_musiclist.setObjectName("verticalLayout_musiclist")
        self.horizontalLayout_label_playlist = QtWidgets.QHBoxLayout()
        self.horizontalLayout_label_playlist.setObjectName("horizontalLayout_save_btn")
        self.label_list_name = QtWidgets.QLabel(self.widget)
        self.label_list_name.setText("PlayList")
        self.label_list_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_list_name.sizePolicy().hasHeightForWidth()
        )
        self.label_list_name.setSizePolicy(sizePolicy)
        self.label_list_name.setStyleSheet('font: 18pt; color: white; font-weight:bold')
        self.label_list_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_name.setObjectName("label_list_name")
        self.horizontalLayout_label_playlist.addWidget(self.label_list_name)

        self.verticalLayout_musiclist.addLayout(self.horizontalLayout_label_playlist)
        self.search_field = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_field.sizePolicy().hasHeightForWidth())
        self.search_field.setSizePolicy(sizePolicy)
        self.search_field.setMaximumSize(QtCore.QSize(16777215, 25))
        self.search_field.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_field.setStyleSheet("border:1px groove white;border-radius:2px;font: 9pt;color: white;")
        self.search_field.setFixedWidth(250)
        self.search_field.setFixedHeight(25)
        self.search_field.setText("")
        self.search_field.setObjectName("lineEdit")
        self.verticalLayout_musiclist.addWidget(self.search_field)
        self.playlist_listWidget = QtWidgets.QListWidget(self.widget)
        self.playlist_listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        with open('styles/playlist.css', 'r') as f:
            playlist_style = f.read()
        self.playlist_listWidget.setStyleSheet(playlist_style)
        self.playlist_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.playlist_listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.playlist_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.playlist_listWidget.setHorizontalScrollMode(
            QtWidgets.QAbstractItemView.ScrollPerItem
        )
        self.playlist_listWidget.setObjectName("listWidget")
        self.verticalLayout_musiclist.addWidget(self.playlist_listWidget)
        self.pushButton_song_find = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_song_find.sizePolicy().hasHeightForWidth()
        )
        self.pushButton_song_find.setSizePolicy(sizePolicy)
        self.pushButton_song_find.setMaximumSize(QtCore.QSize(16777215, 15))
        self.pushButton_song_find.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_song_find.setFocusPolicy(QtCore.Qt.NoFocus)

        self.pushButton_song_find.setText("")
        self.pushButton_song_find.setFlat(True)
        self.pushButton_song_find.setObjectName("pushButton_song_find")

        self.verticalLayout_musiclist.addWidget(self.pushButton_song_find)
        self.verticalLayout_musiclist.setStretch(0, 1)
        self.verticalLayout_musiclist.setStretch(1, 1)
        self.verticalLayout_musiclist.setStretch(2, 10)
        self.verticalLayout_musiclist.setStretch(3, 1)

        self.horizontalLayout_body.addLayout(self.verticalLayout_musiclist)

        # adding vis a and info panel
        self.widget_song_info = QtWidgets.QWidget(self.widget)
        self.widget_song_info.setObjectName("widget_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_song_info)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hLayout_vis = QtWidgets.QHBoxLayout()
        self.hLayout_vis.setContentsMargins(5, 5, 5, 5)
        self.hLayout_vis.setObjectName("horizontalLayout_pic")
        self.widget_vis = QtWidgets.QWidget(self.widget_song_info)
        self.widget_vis.setMinimumSize(QtCore.QSize(300, 300))
        self.widget_vis.setMaximumSize(QtCore.QSize(300, 300))
        self.widget_vis.setObjectName("widget_pic")
        self.label_pic = QtWidgets.QLabel(self.widget_vis)
        self.label_pic.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.label_pic.setMinimumSize(QtCore.QSize(300, 300))
        self.label_pic.setMaximumSize(QtCore.QSize(300, 300))
        self.label_pic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pic.setText("")

        self.label_pic.setScaledContents(True)
        self.label_pic.setObjectName("label_pic")

        self.hLayout_vis.addWidget(self.widget_vis)
        self.verticalLayout_4.addLayout(self.hLayout_vis)
        self.label_info = QtWidgets.QLabel(self.widget_song_info)
        self.label_info.setStyleSheet('font: 8pt; color: white;')
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_4.addWidget(self.label_info)
        self.hLayout = QtWidgets.QHBoxLayout()
        self.hLayout.setSpacing(0)
        self.hLayout.setObjectName("horizontalLayout")
        self.AudioInfo_listWidget = QtWidgets.QListWidget(self.widget_song_info)
        self.AudioInfo_listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AudioInfo_listWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.AudioInfo_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AudioInfo_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AudioInfo_listWidget.setObjectName("listWidget_3")

        self.hLayout.addWidget(self.AudioInfo_listWidget)
        self.hLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_4.addLayout(self.hLayout)
        self.horizontalLayout_body.addWidget(
            self.widget_song_info, 0, QtCore.Qt.AlignVCenter
        )
        self.horizontalLayout_body.setStretch(1, 4)
        self.horizontalLayout_body.setStretch(2, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_body)

        # lyrics 
        self.vLayout_lyrics = QtWidgets.QVBoxLayout()
        self.vLayout_lyrics.setObjectName("vLayout_lrc")
        self.label_name = QtWidgets.QLabel(self.widget)
        self.label_name.setStyleSheet('margin: 20px;font: 15pt; color:white; font-weight:bold;')
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("labelName")
        self.label_name.setText("Lyrics")
        self.vLayout_lyrics.addWidget(self.label_name)
        self.lyric_listWidget = QtWidgets.QListWidget(self.widget)
        self.lyric_listWidget.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor)
        )
        self.lyric_listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        with open('styles/lyricList.css', 'r') as f:
            style_lyricList = f.read()
        self.lyric_listWidget.setStyleSheet(style_lyricList)
        self.lyric_listWidget.setLocale(
            QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.HongKong)
        )
        self.lyric_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lyric_listWidget.setObjectName("lyrics_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.lyric_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lyric_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lyric_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lyric_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lyric_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.lyric_listWidget.addItem(item)

        self.vLayout_lyrics.addWidget(self.lyric_listWidget)
        self.horizontalLayout_body.addLayout(self.vLayout_lyrics)

        self.widget_bottom = QtWidgets.QWidget(self.widget)
        self.widget_bottom.setMinimumSize(QtCore.QSize(0, 120))
        self.widget_bottom.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_bottom.setStyleSheet("background:rgb(99, 5, 5);border-bottom-right-radius:10px;border-bottom-left-radius:10px;")
        self.widget_bottom.setObjectName("widget_bottom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_bottom)
        self.horizontalLayout_6.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.layout_left_controls = QtWidgets.QHBoxLayout()
        self.layout_left_controls.setSpacing(10)
        self.layout_left_controls.setObjectName("horizontalLayout_left_btn")
        self.pushButton_path = QtWidgets.QPushButton(self.widget_bottom)
        self.pushButton_path.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_path.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_path.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_path.setStyleSheet("image: url(images/folder_add.png);")
        self.pushButton_path.setText("")
        self.pushButton_path.setFlat(True)
        self.pushButton_path.setObjectName("pushButton_path")
        self.layout_left_controls.addWidget(self.pushButton_path)
        self.button_prev = QtWidgets.QPushButton(self.widget_bottom)
        self.button_prev.setMinimumSize(QtCore.QSize(30, 30))
        self.button_prev.setMaximumSize(QtCore.QSize(30, 30))
        self.button_prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_prev.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_prev.setStyleSheet("image: url(images/previous.png);")
        self.button_prev.setText("")
        self.button_prev.setFlat(True)
        self.button_prev.setObjectName("pushButton_prev")
        self.layout_left_controls.addWidget(self.button_prev)
        self.btn_play = QtWidgets.QPushButton(self.widget_bottom)
        self.btn_play.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_play.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_play.setStyleSheet("image: url(images/play.png);")
        self.btn_play.setText("")
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.layout_left_controls.addWidget(self.btn_play)
        self.btn_next = QtWidgets.QPushButton(self.widget_bottom)
        self.btn_next.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_next.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_next.setStyleSheet("image: url(images/next.png);")
        self.btn_next.setText("")
        self.btn_next.setFlat(True)
        self.btn_next.setObjectName("pushButton_next")
        self.layout_left_controls.addWidget(self.btn_next)

        self.horizontalLayout_6.addLayout(self.layout_left_controls)
        self.label_time_start = QtWidgets.QLabel(self.widget_bottom)
        self.label_time_start.setMinimumSize(QtCore.QSize(0, 0))
        self.label_time_start.setStyleSheet('font: 9pt;' "color: white;")
        self.label_time_start.setObjectName("label_time_start")
        self.horizontalLayout_6.addWidget(self.label_time_start)
        self.hSlider = QtWidgets.QSlider(self.widget_bottom)
        self.hSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        with open('styles/h_slider.css', 'r') as f:
            h_slider_style = f.read()
        self.hSlider.setStyleSheet(h_slider_style)

        self.hSlider.setProperty("value", 0)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_6.addWidget(self.hSlider)
        self.label_time_end = QtWidgets.QLabel(self.widget_bottom)
        self.label_time_end.setMinimumSize(QtCore.QSize(0, 0))
        self.label_time_end.setStyleSheet('font: 9pt;' "color: white;")
        self.label_time_end.setObjectName("label_time_end")
        self.horizontalLayout_6.addWidget(self.label_time_end)
        self.verticalLayout_5.addWidget(self.widget_bottom)
        self.horizontalLayout_9.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.updateUiTranslatation(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def updateUiTranslatation(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The New Musicplayer"))
        self.label_list_name.setText(_translate("MainWindow", "Playlist"))
        # self.pushButton_save_to_playlist.setText(_translate("MainWindow", "Save"))
        self.search_field.setPlaceholderText(_translate("MainWindow", "SEARCH"))
        self.label_name.setText(_translate("MainWindow", "Lyrics"))
        __sortingEnabled = self.lyric_listWidget.isSortingEnabled()
        self.lyric_listWidget.setSortingEnabled(False)
        item = self.lyric_listWidget.item(5)
        item.setText(_translate("MainWindow", "The lyrics will appear here"))
        item = self.lyric_listWidget.item(6)
        self.lyric_listWidget.setSortingEnabled(__sortingEnabled)
        self.label_info.setText(_translate("MainWindow", "MUSIC INFO"))
        __sortingEnabled = self.AudioInfo_listWidget.isSortingEnabled()
        self.AudioInfo_listWidget.setSortingEnabled(False)
        self.AudioInfo_listWidget.setSortingEnabled(__sortingEnabled)
        self.label_time_start.setText(_translate("MainWindow", "00:00"))
        self.label_time_end.setText(_translate("MainWindow", "00:00"))